### ISSUE TITLE
Button Unresponsiveness On Some Machines

### ISSUE THREAD

**Issue by emrameduseljac** [oss-slu/SpeechTranscription#160]
Buttons in the application are unresponsive on some machines. Clicking the buttons does not trigger any visible action/expected response, and if it does, it does so very slowly. At times, when trying to click some buttons, errors will appear in the terminal. This issue is inconsistent across different machines.

When a button is clicked, it should trigger the associated functionality such as uploading a file, starting a recording, playing or pausing the audio, etc. The application should respond consistently across all machines.

To see this bug, launch the application on the affected machine.
Begin a new audio file, and click any button.
Observe that the button clicks do not trigger a response, at all or very slowly.

**Device information**
 - MacOS
 - Python Version: 3.11.5

**Comment by kate-holdener** [comment]
@emrameduseljac this might be relevant https://github.com/python/cpython/issues/110218
