### ISSUE TITLE
No module named 'language_tool_python'

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/SpeechTranscription#25]
I am trying to run this code on my Mac.
After installing the dependencies with: `pip3 install -r requirements.txt`, I ran: `python3 GUY.py`, which resulted in the following 
```
error:
python3 GUI.py 
Traceback (most recent call last):
  File "GUI.py", line 11, in <module>
    import addConventions
  File "/Users/holdenerea/repos/SpeechTranscription/addConventions.py", line 2, in <module>
    import language_tool_python
ModuleNotFoundError: No module named 'language_tool_python
```

**Comment by ahediger** [comment]
This should be resolved by the new install requirements we are pushing

**Comment by ahediger** [comment]
As the issue stems from installation requirements I'm not quite sure how to test to ensure that everything is installed appropriately.

**Comment by kate-holdener** [comment]
I verified that this issue is now resolved.
