### ISSUE TITLE
Grammar check

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/SpeechTranscription#56]
I typed "Dogs is loud" in the text area and clicked "Grammar check". My text showed up on the right side of the screen without any error indications. 

<img width="1389" alt="Screen Shot 2023-04-05 at 9 47 00 AM" src="https://user-images.githubusercontent.com/42073871/230118968-8ac61e9f-35f6-4899-b67e-ccd1a7b9a7bf.png">

Not sure if this particular case should be working at this point or not, but I think I've see you demonstrate a similar case reporting a grammar error

**Comment by jakewahle** [comment]
The library we are using for grammar checking, language_tool_python, unfortunately does not recognize any error in this case. This can be verified at [this website](https://languagetool.org/spellchecking-english), from which the library is adapted. 

![Screenshot (36)](https://user-images.githubusercontent.com/37639498/232146847-bd5bc882-be57-4ef7-aefa-8e8b17853343.png)

It may be worth changing this library to a different one in the future; it shouldn't be too difficult to do so with how our code is set up.
